server.port=8081

# spring.datasource.url=jdbc:mysql://localhost:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.username=app
# spring.datasource.password=app
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.security=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SQL statements were removed from application.properties and moved to a Flyway migration:
# src/main/resources/db/migration/V1__create_app_user.sql

# spring.autoconfigure.exclude=\
# org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
# org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
# logging.level.org.springframework.security=DEBUG