server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cards?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none      # Deixa o Flyway gerenciar tudo
    properties:
      hibernate.format_sql: true
      # hibernate.dialect pode ser omitido; o Hibernate detecta MySQL

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    validate-on-migrate: false  # Ignora validação em desenvolvimento
    out-of-order: true          # Permite migrações fora de ordem
    baseline-on-migrate: true   # Cria baseline automático se necessário

jwt:
  issuer: users-cards-api
  audience: users-cards-web
  access-ttl-minutes: 15
  secret-base64: ${JWT_SECRET_BASE64:}   # se o seu JwtService usa Dotenv, esse campo nem é lido

internal.secret: ${INTERNAL_API_SECRET:change-me}

springdoc.swagger-ui.path: /swagger